<script setup>
defineProps({ variant: { type: String, default: 'news-grid' }, count: { type: Number, default: 6 } });
</script>

<template>
  <div class="app-skeleton" aria-busy="true" aria-label="در حال بارگذاری">
    <template v-if="variant === 'home'">
      <div class="grid grid-cols-1 gap-8 lg:grid-cols-12"><aside class="order-2 space-y-8 lg:order-1 lg:col-span-2"><div v-for="block in 2" :key="block" class="space-y-3"><i class="ds-skeleton block h-6 w-2/3"></i><div v-for="line in 5" :key="line" class="flex gap-3 border-b border-divider py-3"><i class="ds-skeleton h-6 w-8 shrink-0"></i><i class="ds-skeleton h-4 flex-1"></i></div></div></aside><main class="order-1 space-y-8 lg:order-2 lg:col-span-7"><div class="overflow-hidden rounded-[1.2rem] bg-navy p-5 sm:p-8"><i class="ds-skeleton block aspect-[16/10] w-full opacity-30"></i><div class="-mt-24 space-y-4"><i class="ds-skeleton block h-5 w-24"></i><i class="ds-skeleton block h-10 w-11/12"></i><i class="ds-skeleton block h-5 w-3/4"></i></div></div><div class="grid gap-5 sm:grid-cols-2"><div v-for="item in 6" :key="item" class="ds-skeleton-card"><i class="ds-skeleton block aspect-[16/10] w-full"></i><i class="ds-skeleton mt-4 block h-4 w-4/5"></i><i class="ds-skeleton mt-2 block h-3 w-2/5"></i></div></div></main><aside class="order-3 space-y-8 lg:col-span-3"><div v-for="block in 3" :key="block" class="space-y-3"><i class="ds-skeleton block h-6 w-1/2"></i><i v-for="line in 4" :key="line" class="ds-skeleton block h-4 w-full"></i></div></aside></div>
    </template>
    <template v-else-if="variant === 'article'"><div class="mx-auto max-w-5xl"><i class="ds-skeleton mb-5 block h-3 w-1/3"></i><div class="article-surface rounded-xl bg-white p-5 sm:p-8"><i class="ds-skeleton block h-5 w-20"></i><i class="ds-skeleton mt-5 block h-10 w-11/12 sm:h-14"></i><i class="ds-skeleton mt-3 block h-4 w-2/5"></i><i class="ds-skeleton mt-7 block aspect-video w-full"></i><i class="ds-skeleton mt-7 block h-5 w-4/5"></i><i v-for="line in 5" :key="line" class="ds-skeleton mt-3 block h-4" :class="line === 5 ? 'w-2/3' : 'w-full'"></i></div></div></template>
    <template v-else-if="variant === 'table'"><div class="space-y-4"><div class="ds-skeleton-card grid gap-3 sm:grid-cols-3"><i v-for="item in 3" :key="item" class="ds-skeleton h-10 w-full"></i></div><div class="overflow-hidden rounded-xl border border-divider bg-white"><div v-for="row in count" :key="row" class="grid grid-cols-[2fr_1fr_1fr] gap-4 border-b border-divider p-4 last:border-0"><i class="ds-skeleton h-4 w-full"></i><i class="ds-skeleton h-4 w-2/3"></i><i class="ds-skeleton h-8 w-full"></i></div></div></div></template>
    <template v-else-if="variant === 'profile'"><div class="mx-auto max-w-2xl space-y-5"><div v-for="card in 2" :key="card" class="rounded-2xl bg-white p-7 shadow-sm"><i class="ds-skeleton block h-7 w-1/3"></i><i v-for="line in card === 1 ? 2 : 4" :key="line" class="ds-skeleton mt-5 block h-12 w-full"></i></div></div></template>
    <template v-else><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="item in count" :key="item" class="ds-skeleton-card"><i class="ds-skeleton block h-40 w-full"></i><i class="ds-skeleton mt-4 block h-4 w-4/5"></i><i class="ds-skeleton mt-2 block h-3 w-2/5"></i></div></div></template>
  </div>
</template>
